# Generated by Django 5.2.4 on 2025-08-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Social_Platform", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
