# Generated by Django 5.2.4 on 2025-08-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Social_Platform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tuổi"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="firstname",
            field=models.CharField(blank=True, max_length=100, verbose_name="Tên"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="lastname",
            field=models.CharField(blank=True, max_length=100, verbose_name="Họ"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("teacher", "Giáo viên"), ("expert", "Chuyên gia")],
                max_length=20,
                verbose_name="Vai trò",
            ),
        ),
    ]
