# Generated by Django 5.2.4 on 2025-08-07 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Social_Platform", "0002_alter_userprofile_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_login_points", models.IntegerField(default=10)),
                ("upload_file_points", models.IntegerField(default=20)),
                ("create_post_points", models.IntegerField(default=15)),
                ("like_post_points", models.IntegerField(default=2)),
                ("share_post_points", models.IntegerField(default=5)),
                ("comment_points", models.IntegerField(default=3)),
                ("follow_user_points", models.IntegerField(default=5)),
                ("view_paid_file_cost", models.IntegerField(default=5)),
                ("download_paid_file_cost", models.IntegerField(default=10)),
            ],
            options={
                "verbose_name": "Point Settings",
                "verbose_name_plural": "Point Settings",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_daily_points",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Login"),
                            ("upload_file", "Upload File"),
                            ("create_post", "Create Post"),
                            ("like_post", "Like Post"),
                            ("share_post", "Share Post"),
                            ("view_file", "View File"),
                            ("download_file", "Download File"),
                            ("comment", "Comment"),
                            ("follow", "Follow User"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("related_object_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
