# Generated by Django 5.2.4 on 2025-08-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Social_Platform",
            "0003_pointsettings_userprofile_last_daily_points_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pointsettings",
            name="daily_login_points",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_daily_points",
        ),
        migrations.AlterField(
            model_name="pointtransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("upload_file", "Upload File"),
                    ("create_post", "Create Post"),
                    ("like_post", "Like Post"),
                    ("share_post", "Share Post"),
                    ("view_file", "View File"),
                    ("download_file", "Download File"),
                    ("comment", "Comment"),
                    ("follow", "Follow User"),
                ],
                max_length=20,
            ),
        ),
    ]
