# Generated by Django 5.2.4 on 2025-08-08 01:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Social_Platform", "0004_remove_pointsettings_daily_login_points_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pointtransaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Point Transaction",
                "verbose_name_plural": "Point Transactions",
            },
        ),
        migrations.AddField(
            model_name="pointsettings",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="pointsettings",
            name="daily_login_points",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Điểm đăng nhập hàng ngày"
            ),
        ),
        migrations.AddField(
            model_name="pointsettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_daily_points",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ngày nhận điểm hàng ngày cuối"
            ),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="comment_points",
            field=models.PositiveIntegerField(default=3, verbose_name="Điểm comment"),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="create_post_points",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Điểm tạo bài viết"
            ),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="download_paid_file_cost",
            field=models.PositiveIntegerField(
                default=20, verbose_name="Chi phí download file có phí"
            ),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="follow_user_points",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Điểm follow user"
            ),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="like_post_points",
            field=models.PositiveIntegerField(
                default=2, verbose_name="Điểm like bài viết"
            ),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="share_post_points",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Điểm share bài viết"
            ),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="upload_file_points",
            field=models.PositiveIntegerField(
                default=15, verbose_name="Điểm upload file"
            ),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="view_paid_file_cost",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Chi phí xem file có phí"
            ),
        ),
        migrations.AlterField(
            model_name="pointtransaction",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="pointtransaction",
            name="description",
            field=models.TextField(blank=True, verbose_name="Mô tả"),
        ),
        migrations.AlterField(
            model_name="pointtransaction",
            name="points",
            field=models.IntegerField(verbose_name="Điểm (+ là cộng, - là trừ)"),
        ),
        migrations.AlterField(
            model_name="pointtransaction",
            name="related_object_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID đối tượng liên quan"
            ),
        ),
        migrations.AlterField(
            model_name="pointtransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("create_post", "Tạo bài viết"),
                    ("like_post", "Like bài viết"),
                    ("share_post", "Share bài viết"),
                    ("comment", "Bình luận"),
                    ("follow", "Follow user"),
                    ("upload_file", "Upload file"),
                    ("view_file", "Xem file có phí"),
                    ("download_file", "Download file có phí"),
                    ("daily_login", "Đăng nhập hàng ngày"),
                    ("manual", "Thêm thủ công"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="points",
            field=models.PositiveIntegerField(default=0, verbose_name="Điểm"),
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="Social_Platform.post",
                        verbose_name="Bài viết",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người share",
                    ),
                ),
            ],
            options={
                "verbose_name": "Share",
                "verbose_name_plural": "Shares",
                "ordering": ["-created_at"],
                "unique_together": {("user", "post")},
            },
        ),
    ]
