# Generated by Django 5.2.4 on 2025-08-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Social_Platform", "0005_alter_pointtransaction_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pointtransaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="pointsettings",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="pointsettings",
            name="daily_login_points",
        ),
        migrations.RemoveField(
            model_name="pointsettings",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_daily_points",
        ),
        migrations.AddField(
            model_name="pointsettings",
            name="view_free_file_cost",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="comment_points",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="create_post_points",
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="download_paid_file_cost",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="follow_user_points",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="like_post_points",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="share_post_points",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="upload_file_points",
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="view_paid_file_cost",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="pointtransaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pointtransaction",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pointtransaction",
            name="points",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="pointtransaction",
            name="related_object_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pointtransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("upload_file", "Upload File"),
                    ("create_post", "Create Post"),
                    ("like_post", "Like Post"),
                    ("share_post", "Share Post"),
                    ("view_file", "View File"),
                    ("download_file", "Download File"),
                    ("comment", "Comment"),
                    ("follow", "Follow User"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Share",
        ),
    ]
