# Generated by Django 5.2.4 on 2025-08-08 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Social_Platform", "0006_alter_pointtransaction_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pointsettings",
            name="view_free_file_cost",
        ),
    ]
