# Generated by Django 5.2.4 on 2025-08-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Social_Platform", "0007_remove_pointsettings_view_free_file_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointsettings",
            name="download_free_file_cost",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="pointsettings",
            name="view_free_file_cost",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="pointtransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("upload_file", "Upload File"),
                    ("create_post", "Create Post"),
                    ("like_post", "Like Post"),
                    ("share_post", "Share Post"),
                    ("view_file", "View File"),
                    ("download_file", "Download File"),
                    ("view_free_file", "View Free File"),
                    ("download_free_file", "Download Free File"),
                    ("comment", "Comment"),
                    ("follow", "Follow User"),
                ],
                max_length=20,
            ),
        ),
    ]
