# Generated by Django 5.2.4 on 2025-08-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Social_Platform", "0008_pointsettings_download_free_file_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointsettings",
            name="comment_points",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="create_post_points",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="like_post_points",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="pointtransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("upload_file", "Upload File"),
                    ("create_post", "Create Post"),
                    ("like_post", "Like Post"),
                    ("unlike_post", "Unlike Post"),
                    ("share_post", "Share Post"),
                    ("view_file", "View File"),
                    ("download_file", "Download File"),
                    ("view_free_file", "View Free File"),
                    ("download_free_file", "Download Free File"),
                    ("comment", "Comment"),
                    ("follow", "Follow User"),
                ],
                max_length=20,
            ),
        ),
    ]
