# Generated by Django 5.2.4 on 2025-08-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Social_Platform", "0009_alter_pointsettings_comment_points_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pointsettings",
            name="download_paid_file_cost",
        ),
        migrations.RemoveField(
            model_name="pointsettings",
            name="follow_user_points",
        ),
        migrations.RemoveField(
            model_name="pointsettings",
            name="view_paid_file_cost",
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="share_post_points",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="pointsettings",
            name="upload_file_points",
            field=models.IntegerField(default=10),
        ),
    ]
