# Generated by Django 5.2.3 on 2025-07-24 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File_sharing_platform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='short_description',
            new_name='file_description',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='status',
            new_name='file_status',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_image',
            new_name='file_thumbnail',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_body',
            new_name='file_urls',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='views',
            new_name='file_views',
        ),
        migrations.RemoveField(
            model_name='file',
            name='slug',
        ),
    ]
