# Generated by Django 5.2.4 on 2025-08-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("File_sharing_platform", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="file_price",
        ),
        migrations.AddField(
            model_name="file",
            name="file_points",
            field=models.PositiveIntegerField(default=1, verbose_name="Điểm yêu cầu"),
        ),
    ]
