# Generated by Django 5.2.4 on 2025-08-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("File_sharing_platform", "0002_category_hierarchy"),
    ]

    operations = []
