# Generated by Django 5.2.4 on 2025-08-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("File_sharing_platform", "0002_remove_file_file_price_file_file_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="file_points",
        ),
        migrations.AddField(
            model_name="file",
            name="file_price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
