# Generated by Django 4.0.8 on 2025-07-25 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('File_sharing_platform', '0002_rename_short_description_file_file_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_thumbnail',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='thumbnails/%y/%m/%d'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='File_sharing_platform.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'unique_together': {('user', 'file')},
            },
        ),
    ]
