# Generated by Django 5.2.4 on 2025-08-12 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("File_sharing_platform", "0003_remove_file_file_points_file_file_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extension_type",
                    models.CharField(
                        choices=[
                            ("document", "Văn bản"),
                            ("presentation", "Bài thuyết trình"),
                            ("image", "Ảnh"),
                            ("video", "Video"),
                            ("archive", "Nén"),
                            ("other", "Khác"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="file",
            name="extension",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="File_sharing_platform.fileextension",
            ),
        ),
    ]
