# Generated by Django 4.2.7 on 2025-07-28 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("File_sharing_platform", "0004_fix_slug_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(unique=True)),
                (
                    "file_thumbnail",
                    models.ImageField(
                        blank=True,
                        default="default.jpg",
                        null=True,
                        upload_to="thumbnails/%y/%m/%d",
                    ),
                ),
                ("file_description", models.TextField(blank=True, null=True)),
                ("file_urls", models.FileField(upload_to="uploads/%y/%m/%d")),
                (
                    "file_status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Published")], default=0
                    ),
                ),
                ("file_views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="File_sharing_platform.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Upload",
                "verbose_name_plural": "File Uploads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="file",
            name="download_count",
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
