# Generated by Django 4.2.7 on 2025-07-28 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "File_sharing_platform",
            "0006_fileupload_remove_file_download_count_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveIndex(
            model_name="file",
            name="File_sharin_file_st_4c52ce_idx",
        ),
        migrations.RemoveIndex(
            model_name="file",
            name="File_sharin_categor_accf82_idx",
        ),
        migrations.RemoveIndex(
            model_name="file",
            name="File_sharin_author__629f9a_idx",
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="file",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="file",
            name="file_type",
        ),
        migrations.RemoveField(
            model_name="file",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="file",
            name="tags",
        ),
        migrations.AlterField(
            model_name="file",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="File_sharing_platform.file",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "file")},
        ),
    ]
