# Generated by Django 4.2.7 on 2025-07-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("File_sharing_platform", "0007_favorite_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="file_views",
            new_name="file_downloads",
        ),
    ]
