# Generated by Django 4.2.7 on 2025-07-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("File_sharing_platform", "0008_rename_file_views_file_file_downloads"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_status",
            field=models.IntegerField(
                choices=[(0, "Free"), (1, "For sales")], default=0
            ),
        ),
    ]
