# Generated by Django 5.2.4 on 2025-07-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("File_sharing_platform", "0010_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="thumbnails/%y/%m/%d"
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="file_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="thumbnails/%y/%m/%d"
            ),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
