# Generated by Django 5.2.4 on 2025-08-16 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileattachment",
            name="related_pdf",
            field=models.OneToOneField(
                blank=True,
                help_text="PDF file được tạo từ HTML file này",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_html",
                to="Chatbot.fileattachment",
            ),
        ),
        migrations.AlterField(
            model_name="fileattachment",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("document", "Document"),
                    ("html", "HTML Document"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
