# Generated by Django 5.2.4 on 2025-08-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chatbot", "0002_fileattachment_related_pdf_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileattachment",
            name="related_pdf",
        ),
        migrations.AlterField(
            model_name="fileattachment",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("document", "Document"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
