# Generated by Django 4.2.7 on 2025-07-28 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Chatbot", "0002_chatmessage_attached_file_chatmessage_file_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="ChatSession",
        ),
    ]
